# context/context.py

"""
Repository context generator for ChemToy.

This script walks the repository, collects source files, and writes a
single Markdown context file:

    context/context.md

The generated file is useful for giving an LLM the current state of the
repository in one compact document.

By default it excludes generated outputs such as:

    results/
    __pycache__/
    .git/
    .venv/
    .pytest_cache/

Run locally:

    python context/context.py

GitHub Actions can also run it manually via:

    .github/workflows/context.yml
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from datetime import datetime, timezone


# ---------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------


REPO_ROOT = Path(__file__).resolve().parents[1]

CONTEXT_DIR = REPO_ROOT / "context"

OUTPUT_FILE = CONTEXT_DIR / "context.md"


INCLUDE_EXTENSIONS = {
    ".py",
    ".md",
    ".toml",
    ".yaml",
    ".yml",
    ".txt",
    ".json",
}


EXCLUDE_DIRS = {
    ".git",
    ".github_cache",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "venv",
    "env",
    "__pycache__",
    "build",
    "dist",
    "site",
    ".idea",
    ".vscode",
    "results",
    "data",
}


EXCLUDE_FILES = {
    "context.md",
}


# ---------------------------------------------------------------------
# File record
# ---------------------------------------------------------------------


@dataclass(slots=True)
class FileRecord:
    """
    A source file included in the context document.
    """

    path: Path

    relative_path: Path

    text: str


# ---------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------


def should_skip_path(path: Path) -> bool:
    """
    Return True if a path should be excluded.
    """

    relative = path.relative_to(REPO_ROOT)

    parts = set(relative.parts)

    if parts & EXCLUDE_DIRS:
        return True

    if path.name in EXCLUDE_FILES:
        return True

    return False


def should_include_file(path: Path) -> bool:
    """
    Return True if a file should be included.
    """

    if not path.is_file():
        return False

    if should_skip_path(path):
        return False

    if path.suffix.lower() not in INCLUDE_EXTENSIONS:
        return False

    return True


def read_text_file(path: Path) -> str:
    """
    Read a text file safely.
    """

    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_text(encoding="latin-1")
    except Exception as exc:
        return f"<<ERROR READING FILE: {exc}>>"


def language_for(path: Path) -> str:
    """
    Choose a Markdown code-fence language.
    """

    suffix = path.suffix.lower()

    if suffix == ".py":
        return "python"

    if suffix in {".yml", ".yaml"}:
        return "yaml"

    if suffix == ".toml":
        return "toml"

    if suffix == ".json":
        return "json"

    if suffix == ".md":
        return "markdown"

    return ""


def discover_files() -> list[FileRecord]:
    """
    Discover files to include in the context document.
    """

    records: list[FileRecord] = []

    for path in sorted(REPO_ROOT.rglob("*")):

        if not should_include_file(path):
            continue

        relative_path = path.relative_to(REPO_ROOT)

        records.append(
            FileRecord(
                path=path,
                relative_path=relative_path,
                text=read_text_file(path),
            )
        )

    return records


def repo_tree(records: list[FileRecord]) -> str:
    """
    Build a simple repository tree from included files.
    """

    lines = []

    for record in records:
        lines.append(str(record.relative_path))

    return "\n".join(lines)


def build_context_markdown(records: list[FileRecord]) -> str:
    """
    Build the final Markdown context document.
    """

    timestamp = datetime.now(timezone.utc).isoformat()

    chunks: list[str] = []

    chunks.append("# ChemToy Repository Context")
    chunks.append("")
    chunks.append(f"Generated: `{timestamp}`")
    chunks.append("")
    chunks.append("This file is generated by:")
    chunks.append("")
    chunks.append("```text")
    chunks.append("context/context.py")
    chunks.append("```")
    chunks.append("")
    chunks.append("Generated outputs are intentionally excluded.")
    chunks.append("")
    chunks.append("Excluded directories include:")
    chunks.append("")
    chunks.append("```text")
    chunks.append("\n".join(sorted(EXCLUDE_DIRS)))
    chunks.append("```")
    chunks.append("")
    chunks.append("---")
    chunks.append("")
    chunks.append("## Included file tree")
    chunks.append("")
    chunks.append("```text")
    chunks.append(repo_tree(records))
    chunks.append("```")
    chunks.append("")
    chunks.append("---")
    chunks.append("")
    chunks.append("## File contents")
    chunks.append("")

    for record in records:

        rel = str(record.relative_path)

        chunks.append(f"### `{rel}`")
        chunks.append("")

        lang = language_for(record.relative_path)

        chunks.append(f"```{lang}")
        chunks.append(record.text.rstrip())
        chunks.append("```")
        chunks.append("")

    return "\n".join(chunks).rstrip() + "\n"


def write_context() -> Path:
    """
    Generate context/context.md.
    """

    CONTEXT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    records = discover_files()

    markdown = build_context_markdown(records)

    OUTPUT_FILE.write_text(
        markdown,
        encoding="utf-8",
    )

    return OUTPUT_FILE


def main() -> None:
    """
    CLI entry point.
    """

    output = write_context()

    print(f"Wrote {output.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
